<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../FhirMpi.Application/FhirMpi.Application.csproj" />
    <ProjectReference Include="../FhirMpi.Hl7v2/FhirMpi.Hl7v2.csproj" />
    <ProjectReference Include="../FhirMpi.Storage.Gcp/FhirMpi.Storage.Gcp.csproj" />
    <ProjectReference Include="../FhirMpi.Storage.InMemory/FhirMpi.Storage.InMemory.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
</Project>
