<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../OpenMpi.Application/OpenMpi.Application.csproj" />
    <ProjectReference Include="../OpenMpi.Hl7v2/OpenMpi.Hl7v2.csproj" />
    <ProjectReference Include="../OpenMpi.Storage.Gcp/OpenMpi.Storage.Gcp.csproj" />
    <ProjectReference Include="../OpenMpi.Storage.InMemory/OpenMpi.Storage.InMemory.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
</Project>
