apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-mpi.name" . }}-api
spec:
  selector: { app.kubernetes.io/name: fhir-mpi, app.kubernetes.io/component: api }
  ports: [{ name: http, port: 80, targetPort: http }]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-mpi.name" . }}-mllp
spec:
  selector: { app.kubernetes.io/name: fhir-mpi, app.kubernetes.io/component: mllp }
  ports: [{ name: mllp, port: {{ .Values.service.mllpPort }}, targetPort: mllp }]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-mpi.name" . }}-portal
spec:
  sessionAffinity: {{ .Values.service.portalSessionAffinity }}
  selector: { app.kubernetes.io/name: fhir-mpi, app.kubernetes.io/component: portal }
  ports: [{ name: http, port: 80, targetPort: http }]
